project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
      - section: Lesson notes
        contents: ["lesson_notes/*"]
      - section: Experiments
        contents: ["experiments/*"]
      - section: Papers
        contents: ["papers/*"]
      - section: Math
        contents: ["math/*"]
    

metadata-files: [nbdev.yml, sidebar.yml]