# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fast-intuition',
                'doc_host': 'https://melonkernel.github.io',
                'git_url': 'https://github.com/melonkernel/fast-intuition',
                'lib_path': 'fast_intuition'},
  'syms': {'fast_intuition.core': {'fast_intuition.core.foo': ('core.html#foo', 'fast_intuition/core.py')}}}